bhusalmart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('shop.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import homepage, category_wise, register, product_detail

app_name = 'shop'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('category/<str:category_slug>', category_wise, name='category_wise'),
    path('register', register, name='register'),
    path('product/<str:product_slug>', product_detail, name='product_detail')
]

cms/models.py
from django.db import models


# Create your models here.

class Banner(models.Model):
    caption = models.CharField(max_length=200)
    image = models.ImageField()

shop/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=20)
    slug = AutoSlugField(populate_from='title')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=20)
    slug = AutoSlugField(populate_from='title')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField()
    brand_name = models.CharField(max_length=20)
    price = models.FloatField()
    details = models.TextField(blank=True)


class ProductAttribute(models.Model):
    key = models.CharField(max_length=20)
    value = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    rating = models.IntegerField()
    comment = models.TextField()

    def rating_range(self):
        return range(self.rating)


class WishList(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

shop/forms.py
from django.forms import ModelForm
from .models import ProductReview


class ProductReviewForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ['comment', 'rating']

cms/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, redirect
from .models import Category, Product
from cms.models import Banner
from django.contrib.auth.forms import UserCreationForm
from .forms import ProductReviewForm


# Create your views here.

def homepage(request):
    categories = Category.objects.all()
    banners = Banner.objects.all()
    products = Product.objects.order_by('-id')[:10]
    print(products)
    context = {
        'categories': categories,
        'banners': banners,
        'products': products
    }
    return render(request, 'homepage.html', context)


def category_wise(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()

    context = {
        'categories': categories,
        'category': category,
        'products': category.product_set.all()
    }

    return render(request, 'category_wise.html', context)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }

    return render(request, 'registration/register.html', context)


def product_detail(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    form = ProductReviewForm()

    if request.method == 'POST':
        print(request.POST)
        form = ProductReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()

    context = {
        'product': product,
        'categories': categories,
        'form': form
    }

    return render(request, 'product-detail.html', context)

shop/templates/category_wise.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
     <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h2 class="title">{{ category.title }}</h2>
                    </div>
                </div>
                <!-- section title -->

                {% for product in products %}
                    <!-- Product Single -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="product product-single">
                            <div class="product-thumb">
                                <button class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view
                                </button>

                                {% thumbnail product.image "270x360" crop="center" as im %}

                                    <img src="{{ im.url }}" alt="">

                                {% endthumbnail %}
                            </div>
                            <div class="product-body">
                                <h3 class="product-price">${{  product.price }}</h3>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o empty"></i>
                                </div>
                                <h2 class="product-name"><a href="#">{{ product.title }}</a></h2>
                                <div class="product-btns">
                                    <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
                                    <button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
                                    <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to
                                        Wishlist
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Product Single -->
                {% endfor %}

            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
{% endblock %}

shop/templates/homepage.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
    <div id="home">
        <!-- container -->
        <div class="container">
            <!-- home wrap -->
            <div class="home-wrap">
                <!-- home slick -->
                <div id="home-slick">
                    <!-- banner -->
                    {% for banner in banners %}
                        <div class="banner banner-1">
                            {% thumbnail banner.image "1200x675" crop="center" as im %}
                                <img src="{{ im.url }}" alt="">
                            {% endthumbnail %}
                            <div class="banner-caption text-center">
                                <h1>{{ banner.caption }}</h1>
                                <button class="primary-btn">Shop Now</button>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- /banner -->
                </div>
                <!-- /home slick -->
            </div>
            <!-- /home wrap -->
        </div>
        <!-- /container -->
    </div>

    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h2 class="title">Latest Products</h2>
                    </div>
                </div>
                <!-- section title -->

                {% for product in products %}
                    <!-- Product Single -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="product product-single">
                            <div class="product-thumb">
                                <button class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view
                                </button>

                                {% thumbnail product.image "270x360" crop="center" as im %}

                                    <img src="{{ im.url }}" alt="">

                                {% endthumbnail %}
                            </div>
                            <div class="product-body">
                                <h3 class="product-price">${{  product.price }}</h3>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o empty"></i>
                                </div>
                                <h2 class="product-name"><a href="{% url 'shop:product_detail' product.slug %}">{{ product.title }}</a></h2>
                                <div class="product-btns">
                                    <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
                                    <button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
                                    <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to
                                        Wishlist
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Product Single -->
                {% endfor %}

            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
{% endblock %}

shop/templates/product-detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    <div class="product product-details clearfix">
        <div class="col-md-6">
            <div id="product-main-view">
                <div class="product-view">
                    {% thumbnail product.image "1200x1200" crop="center" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                </div>

            </div>
        </div>
        <div class="col-md-6">
            <div class="product-body">
                <div class="product-label">
                    <span>New</span>
                    <span class="sale">-20%</span>
                </div>
                <h2 class="product-name">{{ product.title }}</h2>
                <h3 class="product-price">{{ product.price }}
                </h3>
                <div>
                    <div class="product-rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o empty"></i>
                    </div>
                    <a href="#">{{ product.productreview_set.count }} Review(s) / Add Review</a>
                </div>
                <p><strong>Availability:</strong> In Stock</p>
                <p><strong>Brand:</strong> {{ product.brand_name }}</p>
                <p>{{ product.details }}</p>


                <div class="product-btns">
                    <div class="qty-input">
                        <span class="text-uppercase">QTY: </span>
                        <input class="input" type="number">
                    </div>
                    <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Wishlist</button>
                    <div class="pull-right">
                        <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
                        <button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
                        <button class="main-btn icon-btn"><i class="fa fa-share-alt"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="product-tab">
                <ul class="tab-nav">
                    <li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
                    <li><a data-toggle="tab" href="#tab2">Reviews (3)</a></li>
                </ul>
                <div class="tab-content">
                    <div id="tab1" class="tab-pane fade in active">
                        {{ product.details }}
                    </div>
                    <div id="tab2" class="tab-pane fade in">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="product-reviews">

                                    {% for review in product.productreview_set.all %}
                                        <div class="single-review">
                                            <div class="review-heading">
                                                <div><a href="#"><i class="fa fa-user-o"></i> {{ review.user.username }}
                                                </a></div>

                                                <div class="review-rating pull-right">

                                                    {% for i in review.rating_range %}
                                                        <i class="fa fa-star"></i>
                                                    {% endfor %}
                                                </div>

                                            </div>
                                            <div class="review-body">
                                                <p>{{ review.comment }}</p>
                                            </div>
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="col-md-6">
                                    <h4 class="text-uppercase">Write Your Review</h4>
                                    <form class="review-form" method="POST"
                                          action="{% url 'shop:product_detail' product.slug %}">

                                        {% csrf_token %}

                                        {% if form.errors %}
                                            <p style="color: red">Please fill all fields</p>
                                        {% endif %}

                                        <div class="form-group">
                                            <textarea name="comment" class="input" placeholder="Your review"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <div class="input-rating">
                                                <strong class="text-uppercase">Your Rating: </strong>
                                                <div class="stars">
                                                    <input type="radio" id="star5" name="rating" value="5"/><label
                                                        for="star5"></label>
                                                    <input type="radio" id="star4" name="rating" value="4"/><label
                                                        for="star4"></label>
                                                    <input type="radio" id="star3" name="rating" value="3"/><label
                                                        for="star3"></label>
                                                    <input type="radio" id="star2" name="rating" value="2"/><label
                                                        for="star2"></label>
                                                    <input type="radio" id="star1" name="rating" value="1"/><label
                                                        for="star1"></label>
                                                </div>
                                            </div>
                                        </div>
                                        <button class="primary-btn">Submit</button>
                                    </form>
                                </div>
                            {% endif %}
                        </div>


                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

shop/templates/test.html
{% extends 'base.html' %}

{% block content %}
    TESTING TESTING
{% endblock %}